---------------------------------------------------------------------
-- FSCMS v1.0 (스키마)
-- 2109.10.01
---------------------------------------------------------------------

-- 데이터_변경이력
CREATE TABLE FS_DATA_CHGHST (
  DATA_CHGHST_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '데이터_변경이력_일련번호',
  USER_ID VARCHAR(255) COMMENT '사용자_아이디',
  MNGR_ID VARCHAR(255) COMMENT '관리자_아이디',
  TABLE_NM VARCHAR(30) NOT NULL COMMENT '테이블_명',
  BFCHG_DATA BLOB COMMENT '변경전_데이터',
  AFTCH_DATA BLOB COMMENT '변경후_데이터',
  REGIST_PLTFOM VARCHAR(20) COMMENT '등록_플랫폼',
  REGIST_BRWSR VARCHAR(20) COMMENT '등록_브라우저',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(DATA_CHGHST_SN, REGIST_DE)
);

	-- 데이터_변경이력 파티션 설정
	ALTER TABLE FS_DATA_CHGHST
	PARTITION BY RANGE (YEAR(REGIST_DE))
	SUBPARTITION BY HASH (MONTH(REGIST_DE))
	SUBPARTITIONS 12 (
		PARTITION data_chghst_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION data_chghst_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION data_chghst_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION data_chghst_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION data_chghst_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION data_chghst_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION data_chghst_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION data_chghst_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION data_chghst_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION data_chghst_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION data_chghst_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION data_chghst_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION data_chghst_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION data_chghst_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION data_chghst_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION data_chghst_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION data_chghst_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION data_chghst_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION data_chghst_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION data_chghst_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION data_chghst_max VALUES LESS THAN MAXVALUE
	);

-- 코드_분류
CREATE TABLE FS_CODE_CL (
  CODE_CL_ID CHAR(3) NOT NULL COMMENT '코드_분류_아이디',
  CODE_CL_NM VARCHAR(30) NOT NULL COMMENT '코드_분류_명',
  CODE_CL_DC VARCHAR(255) COMMENT '코드_분류_설명',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(CODE_CL_ID)
);

-- 코드
CREATE TABLE FS_CODE (
  CODE_ID CHAR(6) NOT NULL COMMENT '코드_아이디',
  CODE_CL_ID CHAR(3) NOT NULL COMMENT '코드_분류_아이디',
  CODE_NM VARCHAR(60) NOT NULL COMMENT '코드_명',
  CODE_DC VARCHAR(255) COMMENT '코드_설명',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(CODE_ID),
  FOREIGN KEY(CODE_CL_ID) REFERENCES FS_CODE_CL(CODE_CL_ID)
);

-- 코드_상세
CREATE TABLE FS_CODE_DETAIL (
  CODE_DETAIL_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '코드_상세_일련번호',
  CODE_ID CHAR(6) NOT NULL COMMENT '코드_아이디',
  CODE_DETAIL_ID VARCHAR(15) NOT NULL COMMENT '코드_상세_아이디',
  CODE_DETAIL_NM VARCHAR(30) NOT NULL COMMENT '코드_상세_명',
  CODE_DETAIL_DC VARCHAR(255) COMMENT '코드_상세_설명',
  CODE_DETAIL_ORDR SMALLINT(3) NOT NULL COMMENT '코드_상세_순서',
  DELETE_AT CHAR(1) NOT NULL COMMENT '삭제_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(CODE_DETAIL_SN),
  FOREIGN KEY(CODE_ID) REFERENCES FS_CODE(CODE_ID)
);

-- 관리자_역할
CREATE TABLE FS_MNGR_ROLE (
  ROLE_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '역할_일련번호',
  ROLE_NM VARCHAR(20) NOT NULL COMMENT '역할_명',
  ROLE_ORDR SMALLINT(3) NOT NULL COMMENT '역할_순서',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(ROLE_SN)
);

-- 관리자 정보
CREATE TABLE FS_MNGR (
  MNGR_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '관리자_일련번호',
  ROLE_SN INT(11) NOT NULL COMMENT '역할_일련번호',
  ACC_SN INT(11) COMMENT '연결_일련번호',
  MNGR_ID VARCHAR(255) NOT NULL COMMENT '관리자_아이디',
  MNGR_PW VARCHAR(255) COMMENT '관리자_비밀번호',
  MNGR_NM VARCHAR(255) NOT NULL COMMENT '관리자_명',
  LOCK_CO SMALLINT(3) NOT NULL DEFAULT 0 COMMENT '잠금_개수',
  LOCK_DE DATETIME COMMENT '잠금_일자',
  MNGR_SALT VARCHAR(255) COMMENT '관리자_솔트',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(MNGR_SN),
  FOREIGN KEY(ROLE_SN) REFERENCES FS_MNGR_ROLE(ROLE_SN)
);

-- 관리자_로그인_이력
CREATE TABLE FS_MNGR_LOGIN_HIST (
  LOGIN_HIST_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '로그인_이력_일련번호',
  MNGR_SN INT(11) NOT NULL COMMENT '관리자_일련번호',
  SESION_ID VARCHAR(100) NOT NULL COMMENT '세션_아이디',
  LOGIN_IP VARCHAR(20) NOT NULL COMMENT '로그인_아이피',
  LOGIN_PLTFOM VARCHAR(20) COMMENT '로그인_플랫폼',
  LOGIN_BRWSR_NM VARCHAR(20) NOT NULL COMMENT '로그인_브라우저_명',
  LOGIN_BRWSR_VER VARCHAR(10) COMMENT '로그인_브라우저_버전',
  LOGIN_BGNDE DATETIME NOT NULL COMMENT '로그인_시작일',
  LOGIN_ENDDE DATETIME COMMENT '로그인_종료일',
  PRIMARY KEY(LOGIN_HIST_SN, LOGIN_BGNDE)
);

	-- 관리자_로그인_이력 세션_아이디 인덱스 생성 (불가 x 파티션 테이블은 별도의 FK 생성안됨)
	-- CREATE INDEX SESION_ID ON FS_MNGR_LOGIN_HIST (SESION_ID);
	-- 관리자_로그인_이력 파티션 설정
	ALTER TABLE FS_MNGR_LOGIN_HIST
	PARTITION BY RANGE (YEAR(LOGIN_BGNDE))
	SUBPARTITION BY HASH (MONTH(LOGIN_BGNDE))
	SUBPARTITIONS 12 (
		PARTITION mngr_login_hist_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION mngr_login_hist_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION mngr_login_hist_max VALUES LESS THAN MAXVALUE
	);

-- 관리자_메뉴
CREATE TABLE FS_MNGR_MENU (
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  ACC_SN INT(11) COMMENT '연결_일련번호',
  MENU_BEST_SN CHAR(13) COMMENT '메뉴_최상위_일련번호',
  MENU_UPPER_SN CHAR(13) COMMENT '메뉴_상위_일련번호',
  MENU_ORDR SMALLINT(3) NOT NULL COMMENT '메뉴_순서',
  MENU_DP SMALLINT(3) NOT NULL COMMENT '메뉴_깊이',
  MENU_NM VARCHAR(60) NOT NULL COMMENT '메뉴_명',
  MENU_CNNC_TY CHAR(1) NOT NULL DEFAULT '0' COMMENT '메뉴_연결_타입',
  MENU_ITNADR VARCHAR(255) COMMENT '메뉴_인터넷주소',
  MENU_ITNADR_TY CHAR(1) COMMENT '메뉴_인터넷주소_타입',
  MENU_TRGT VARCHAR(10) NOT NULL DEFAULT '_self' COMMENT '메뉴_타겟',
  MENU_PARAMTR VARCHAR(255) COMMENT '메뉴_파라미터',
  ACTVTY_AT CHAR(1) NOT NULL COMMENT '활성_여부',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  MENU_LINK VARCHAR(255) COMMENT '메뉴_링크',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(MENU_SN)
);

-- 관리자_메뉴_연결
CREATE TABLE FS_MNGR_MENU_ACC (
  MENU_ACC_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '메뉴_연결_일련번호',
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  ROLE_SN INT(11) NOT NULL COMMENT '역할_일련번호',
  AUTHOR_REDNG CHAR(1) NOT NULL COMMENT '권한_읽기',
  AUTHOR_REGIST CHAR(1) NOT NULL COMMENT '권한_등록',
  PRIMARY KEY(MENU_ACC_SN),
  FOREIGN KEY(MENU_SN) REFERENCES FS_MNGR_MENU(MENU_SN),
  FOREIGN KEY(ROLE_SN) REFERENCES FS_MNGR_ROLE(ROLE_SN)
);

-- 사용자_역할
CREATE TABLE FS_USER_ROLE (
  ROLE_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '역할_일련번호',
  ROLE_NM VARCHAR(20) NOT NULL COMMENT '역할_명',
  ROLE_ORDR SMALLINT(3) NOT NULL COMMENT '역할_순서',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(ROLE_SN)
);

-- 사용자
CREATE TABLE FS_USER (
  USER_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '사용자_일련번호',
  ROLE_SN INT(11) NOT NULL COMMENT '역할_일련번호',
  USER_ID VARCHAR(255) NOT NULL COMMENT '사용자_아이디',
  USER_PW VARCHAR(255) COMMENT '사용자_비밀번호',
  USER_NM VARCHAR(255) NOT NULL COMMENT '사용자_명',
  USER_TELNO VARCHAR(255) COMMENT '사용자_전화번호',
  USER_MBTLNUM VARCHAR(255) COMMENT '사용자_휴대폰번호',
  USER_MBTLNUM_RECPTN_AT CHAR(1) COMMENT '사용자_휴대폰번호_수신_여부',
  USER_EMAIL VARCHAR(255) COMMENT '사용자_이메일',
  USER_EMAIL_RECPTN_AT CHAR(1) COMMENT '사용자_이메일_수신_여부',
  USER_ZIP VARCHAR(255) COMMENT '사용자_우편번호',
  USER_ADRES_BASS VARCHAR(255) COMMENT '사용자_주소_기본',
  USER_ADRES_DETAIL VARCHAR(255) COMMENT '사용자_주소_상세',
  USER_RM TEXT COMMENT '사용자_비고',
  USER_SALT VARCHAR(255) COMMENT '사용자_솔트',
  USER_STTUS CHAR(1) NOT NULL COMMENT '사용자_상태',
  LOGIN_DE DATETIME COMMENT '로그인_일자',
  LOCK_CO SMALLINT(3) NOT NULL DEFAULT 0 COMMENT '잠금_개수',
  LOCK_DE DATETIME COMMENT '잠금_일자',
  VIRTL_SN VARCHAR(255) COMMENT '가상_일련번호',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  NICK_NM varchar(255) DEFAULT NULL COMMNET '별명',
  NOTE_SN varchar(45) DEFAULT NULL COMMENT '인증수첩번호',
  HINT varchar(100) DEFAULT NULL  COMMENT '비밀번호_힌트',
  HINT_ANSWER varchar(255) DEFAULT NULL COMMENT '힌트_응답',
  EXPIRE_DE datetime DEFAULT NULL COMMENT '2년_인증 만료일',
  PRIMARY KEY(USER_SN),
  FOREIGN KEY(ROLE_SN) REFERENCES FS_USER_ROLE(ROLE_SN)
);

-- 사용자_메뉴
CREATE TABLE FS_USER_MENU (
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  ACC_SN INT(11) COMMENT '연결_일련번호',
  MENU_BEST_SN CHAR(13) COMMENT '메뉴_최상위_일련번호',
  MENU_UPPER_SN CHAR(13) COMMENT '메뉴_상위_일련번호',
  MENU_ORDR SMALLINT(3) NOT NULL COMMENT '메뉴_순서',
  MENU_DP SMALLINT(3) NOT NULL COMMENT '메뉴_깊이',
  MENU_NM VARCHAR(60) NOT NULL COMMENT '메뉴_명',
  MENU_CNNC_TY CHAR(1) NOT NULL DEFAULT '0' COMMENT '메뉴_연결_타입',
  MENU_ITNADR VARCHAR(255) COMMENT '메뉴_인터넷주소',
  MENU_ITNADR_TY CHAR(1) COMMENT '메뉴_인터넷주소_타입',
  MENU_TRGT VARCHAR(10) NOT NULL DEFAULT '_self' COMMENT '메뉴_타겟',
  MENU_PARAMTR VARCHAR(255) COMMENT '메뉴_파라미터',
  MENU_TAG TEXT COMMENT '메뉴_태그',
  MENU_CLASS VARCHAR(255) COMMENT '메뉴_클래스',
  MENU_FILE_IMAGE VARCHAR(200) COMMENT '메뉴_파일_이미지',
  MENU_FLPTH VARCHAR(255) COMMENT '메뉴_파일경로',
  ACTVTY_AT CHAR(1) NOT NULL COMMENT '활성_여부',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  MENU_LINK VARCHAR(255) COMMENT '메뉴_링크',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(MENU_SN)
);

-- 사용자_메뉴_연결
CREATE TABLE FS_USER_MENU_ACC (
  MENU_ACC_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '메뉴_연결_일련번호',
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  ROLE_SN INT(11) NOT NULL COMMENT '역할_일련번호',
  PRIMARY KEY(MENU_ACC_SN),
  FOREIGN KEY(MENU_SN) REFERENCES FS_USER_MENU(MENU_SN),
  FOREIGN KEY(ROLE_SN) REFERENCES FS_USER_ROLE(ROLE_SN)
);

-- 사이트
CREATE TABLE FS_SITE (
  SITE_NM VARCHAR(60) NOT NULL COMMENT '사이트_명',
  ROLE_SN INT(11) COMMENT '역할_일련번호',
  OPEN_DE VARCHAR(10) COMMENT '오픈_일자',
  DPLCT_LOGIN_AT CHAR(1) NOT NULL DEFAULT 'N' COMMENT '중복_로그인_여부',
  LOGIN_FAILR_LOCK_CO SMALLINT(3) NOT NULL DEFAULT 0 COMMENT '로그인_실패_잠금_개수',
  ACTVTY_AT CHAR(1) NOT NULL COMMENT '활성_여부',
  SNS_USE_AT CHAR(1) NOT NULL DEFAULT 'N' COMMENT 'SNS_사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  FOREIGN KEY(ROLE_SN) REFERENCES FS_USER_ROLE(ROLE_SN)
);

-- 개인정보_접근_이력
CREATE TABLE FS_INDVDLINFO_ACCES_HIST (
  ACCES_HIST_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '접근_이력_일련번호',
  DATA_CHGHST_SN INT(11) COMMENT '데이터_변경이력_일련번호',
  USER_ID VARCHAR(255) COMMENT '사용자_아이디',
  MNGR_ID VARCHAR(255) COMMENT '관리자_아이디',
  ACCES_HIST_CN VARCHAR(255) NOT NULL COMMENT '접근_이력_내용',
  REGIST_PLTFOM VARCHAR(20) COMMENT '등록_플랫폼',
  REGIST_BRWSR VARCHAR(20) COMMENT '등록_브라우저',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(ACCES_HIST_SN, REGIST_DE)
);

	-- 개인정보_접근_이력 파티션 설정
	ALTER TABLE FSINDVDLINFO_ACCES_HIST
	PARTITION BY RANGE (YEAR(REGIST_DE))
	SUBPARTITION BY HASH (MONTH(REGIST_DE))
	SUBPARTITIONS 12 (
		PARTITION data_chghst_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION data_chghst_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION data_chghst_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION data_chghst_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION data_chghst_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION data_chghst_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION data_chghst_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION data_chghst_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION data_chghst_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION data_chghst_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION data_chghst_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION data_chghst_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION data_chghst_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION data_chghst_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION data_chghst_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION data_chghst_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION data_chghst_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION data_chghst_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION data_chghst_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION data_chghst_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION data_chghst_max VALUES LESS THAN MAXVALUE
	);
	
-- 오류_이력
CREATE TABLE FS_ERROR_HIST (
  ERROR_HIST_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '오류_이력_일련번호',
  ERROR_MSSAGE VARCHAR(255) NOT NULL COMMENT '오류_메시지',
  ERROR_CN BLOB NOT NULL COMMENT '오류_내용',
  ERROR_ITNADR VARCHAR(255) COMMENT '오류_인터넷주소',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(ERROR_HIST_SN, REGIST_DE)
);

	-- 오류_이력 파티션 설정
	ALTER TABLE FS_ERROR_HIST
	PARTITION BY RANGE (YEAR(REGIST_DE))
	SUBPARTITION BY HASH (MONTH(REGIST_DE))
	SUBPARTITIONS 12 (
		PARTITION data_chghst_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION data_chghst_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION data_chghst_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION data_chghst_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION data_chghst_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION data_chghst_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION data_chghst_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION data_chghst_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION data_chghst_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION data_chghst_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION data_chghst_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION data_chghst_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION data_chghst_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION data_chghst_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION data_chghst_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION data_chghst_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION data_chghst_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION data_chghst_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION data_chghst_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION data_chghst_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION data_chghst_max VALUES LESS THAN MAXVALUE
	);

-- 관리자_설정
CREATE TABLE FS_MNGR_ESTBS (
  IP_INTRCP_AT CHAR(1) NOT NULL COMMENT '아이피_차단_여부'
);

-- 관리자_아이피_설정
CREATE TABLE FS_MNGR_IP_ESTBS (
  IP_ESTBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '아이피_설정_일련번호',
  IP_ESTBS_TY CHAR(1) NOT NULL COMMENT '아이피_설정_타입',
  IP_ESTBS_DC VARCHAR(255) COMMENT '아이피_설정_설명',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(IP_ESTBS_SN)
);

-- 첨부파일
CREATE TABLE FS_ATCHMNFL (
  ATCHMNFL_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '첨부파일_일련번호',
  ACC_TY VARCHAR(50) NOT NULL COMMENT '연결_타입',
  ACC_SN VARCHAR(13) NOT NULL COMMENT '연결_일련번호',
  ATCHMNFL_ORDR SMALLINT(3) NOT NULL COMMENT '첨부파일_순서',
  ATCHMNFL_NM VARCHAR(255) NOT NULL COMMENT '첨부파일_명',
  ATCHMNFL_REAL_NM VARCHAR(255) NOT NULL COMMENT '첨부파일_실제_명',
  ATCHMNFL_SIZE INT(11) COMMENT '첨부파일_사이즈',
  ATCHMNFL_TY VARCHAR(50) COMMENT '첨부파일_타입',
  ATCHMNFL_EXTSN VARCHAR(10) COMMENT '첨부파일_확장자',
  ATCHMNFL_RM VARCHAR(50) COMMENT '첨부파일_비고',
  FLPTH VARCHAR(255) NOT NULL COMMENT '파일경로',
  REPRSNT_THUMB_AT CHAR(1) NOT NULL COMMENT '대표_썸네일_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(ATCHMNFL_SN)
);

	-- 인덱스 생성
	CREATE INDEX ACC_TY ON FS_ATCHMNFL(ACC_TY);
	CREATE INDEX ACC_SN ON FS_ATCHMNFL(ACC_SN);

-- 팝업
CREATE TABLE FS_POPUP (
  POPUP_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '팝업_일련번호',
  POPUP_NM VARCHAR(100) NOT NULL COMMENT '팝업_명',
  POPUP_CN BLOB NOT NULL COMMENT '팝업_내용',
  POPUP_TY CHAR(1) NOT NULL COMMENT '팝업_타입',
  POPUP_LINK VARCHAR(200) COMMENT '팝업_링크',
  POPUP_ORDER CHAR(2) COMMENT '팝업_순서',
  WIDTH_LC SMALLINT(4) COMMENT '가로_위치',
  VRTICL_LC SMALLINT(4) COMMENT '세로_위치',
  WIDTH_SIZE SMALLINT(4) COMMENT '가로_사이즈',
  VRTICL_SIZE SMALLINT(4) COMMENT '세로_사이즈',
  POPUP_BGNDE DATETIME COMMENT '팝업_시작일',
  POPUP_ENDDE DATETIME COMMENT '팝업_종료일',
  ATMC_SIZE_AT CHAR(1) NOT NULL COMMENT '자동_사이즈_여부',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(POPUP_SN)
);

-- 배너_설정
CREATE TABLE FS_BANNER_ESTBS (
  BANNER_ESTBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '배너_설정_일련번호',
  BANNER_ESTBS_NM VARCHAR(60) NOT NULL COMMENT '배너_설정_명',
  WIDTH_SIZE SMALLINT(4) COMMENT '가로_사이즈',
  VRTICL_SIZE SMALLINT(4) COMMENT '세로_사이즈',
  BANNER_ESTBS_DC TEXT COMMENT '배너_설정_설명',
  UPLOAD_LMTT_CPCTY SMALLINT(4) COMMENT '업로드_제한_용량',
  OPTN_TAG_AT CHAR(1) NOT NULL COMMENT '옵션_태그_여부',
  OPTN_IMAGE_AT CHAR(1) NOT NULL COMMENT '옵션_이미지_여부',
  OPTN_BCRN_IMAGE_AT CHAR(1) NOT NULL COMMENT '옵션_배경_이미지_여부',
  OPTN_CLASS_AT CHAR(1) NOT NULL COMMENT '옵션_클래스_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(BANNER_ESTBS_SN)
);

-- 배너
CREATE TABLE FS_BANNER (
  BANNER_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '배너_일련번호',
  BANNER_ESTBS_SN INT(11) NOT NULL COMMENT '배너_설정_일련번호',
  BANNER_NM VARCHAR(60) NOT NULL COMMENT '배너_명',
  BANNER_ORDR SMALLINT(3) NOT NULL COMMENT '배너_순서',
  BANNER_BGNDE DATETIME COMMENT '배너_시작일',
  BANNER_ENDDE DATETIME COMMENT '배너_종료일',
  BANNER_ITNADR VARCHAR(255) COMMENT '배너_인터넷주소',
  BANNER_TRGT VARCHAR(10) NOT NULL DEFAULT '_self' COMMENT '배너_타겟',
  TAG_CN BLOB COMMENT '태그_내용',
  ATCHMNFL_IMAGE VARCHAR(200) COMMENT '첨부파일_이미지',
  ATCHMNFL_BCRN_IMAGE VARCHAR(200) COMMENT '첨부파일_배경_이미지',
  FLPTH VARCHAR(255) COMMENT '파일경로',
  CLASS_NM VARCHAR(100) COMMENT '클래스_명',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(BANNER_SN),
  FOREIGN KEY(BANNER_ESTBS_SN) REFERENCES FS_BANNER_ESTBS(BANNER_ESTBS_SN)
);

-- 게시판_스킨
CREATE TABLE FS_BBS_SKN (
  BBS_SKN_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_스킨_일련번호',
  BBS_SKN_BEST_SN INT(11) COMMENT '게시판_스킨_최상위_일련번호',
  BBS_SKN_UPPER_SN INT(11) COMMENT '게시판_스킨_상위_일련번호',
  BBS_SKN_ORDR SMALLINT(3) NOT NULL COMMENT '게시판_스킨_순서',
  BBS_SKN_DP SMALLINT(3) NOT NULL COMMENT '게시판_스킨_깊이',
  BBS_SKN_NM VARCHAR(60) NOT NULL COMMENT '게시판_스킨_명',
  BBS_SKN_CODE VARCHAR(60) COMMENT '게시판_스킨_코드',
  CMMN_VIEW_AT CHAR(1) NOT NULL COMMENT '공통_뷰_여부',
  ATCHMNFL_IMAGE VARCHAR(200) COMMENT '첨부파일_이미지',
  FLPTH VARCHAR(255) COMMENT '파일경로',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(BBS_SKN_SN)
);

-- 게시판_설정
CREATE TABLE FS_BBS_ESTBS (
  BBS_ESTBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_설정_일련번호',
  SKN_SN_DP1 INT(11) NOT NULL COMMENT '스킨_일련번호_깊이1',
  SKN_SN_DP2 INT(11) NOT NULL COMMENT '스킨_일련번호_깊이2',
  BBS_ESTBS_NM VARCHAR(60) NOT NULL COMMENT '게시판_설정_명',
  SJ_LT_LMTT SMALLINT(4) NOT NULL COMMENT '제목_길이_제한',
  LIST_INDICT_CO SMALLINT(3) NOT NULL COMMENT '목록_표시_개수',
  CTGRY_AT CHAR(1) NOT NULL COMMENT '카테고리_여부',
  ATCH_AT CHAR(1) NOT NULL COMMENT '첨부_여부',
  ATCH_SIZE SMALLINT(4) COMMENT '첨부_사이즈',
  THUMB_AT CHAR(1) NOT NULL COMMENT '썸네일_여부',
  ANSWER_AT CHAR(1) NOT NULL COMMENT '답글_여부',
  NOTICE_AT CHAR(1) NOT NULL COMMENT '공지_여부',
  SECRET_AT CHAR(1) NOT NULL COMMENT '비밀_여부',
  SECRET_AT_ALWAYS CHAR(1) NOT NULL COMMENT '비밀_여부_항상',
  RDCNT_DPLCT_AT CHAR(1) NOT NULL COMMENT '조회수_중복_여부',
  REGISTER_NM_TY VARCHAR(10) NOT NULL COMMENT '등록자_명_타입',
  INDICT_DAY_NW SMALLINT(4) NOT NULL COMMENT '표시_일_새글',
  HDER_TAG BLOB COMMENT '헤더_태그',
  HDER_CNTNTS_AT CHAR(1) NOT NULL COMMENT '헤더_콘텐츠_여부',
  FOOT_TAG BLOB COMMENT '푸터_태그',
  FOOT_CNTNTS_AT CHAR(1) NOT NULL COMMENT '푸터_콘텐츠_여부',
  AUTHOR_LIST CHAR(1) NOT NULL COMMENT '권한_목록',
  AUTHOR_REDNG CHAR(1) NOT NULL COMMENT '권한_읽기',
  AUTHOR_REGIST CHAR(1) NOT NULL COMMENT '권한_등록',
  AUTHOR_ANSWER CHAR(1) NOT NULL COMMENT '권한_답글',
  AUTHOR_CM CHAR(1) NOT NULL COMMENT '권한_댓글',
  CM_AT CHAR(1) NOT NULL COMMENT '댓글_여부',
  CM_ANSWER_AT CHAR(1) NOT NULL COMMENT '댓글_답글_여부',
  CM_LT_LMTT_AT CHAR(1) NOT NULL COMMENT '댓글_길이_제한_여부',
  CM_LT_LMTT_SIZE SMALLINT(5) COMMENT '댓글_길이_제한_사이즈',
  CM_NMCHANGE_AT CHAR(1) NOT NULL COMMENT '댓글_명의변경_여부',
  CM_PGNG_AT CHAR(1) NOT NULL COMMENT '댓글_페이징_여부',
  CM_LIST_INDICT_CO SMALLINT(3) COMMENT '댓글_목록_표시_개수',
  CM_SORT VARCHAR(4) NOT NULL COMMENT '댓글_정렬',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(BBS_ESTBS_SN)
);

-- 게시판_카테고리
CREATE TABLE FS_BBS_CTGRY (
  BBS_CTGRY_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_카테고리_일련번호',
  BBS_ESTBS_SN INT(11) NOT NULL COMMENT '게시판_설정_일련번호',
  CTGRY_NM VARCHAR(255) NOT NULL COMMENT '카테고리_명',
  PRIMARY KEY(BBS_CTGRY_SN),
  FOREIGN KEY(BBS_ESTBS_SN) REFERENCES FS_BBS_ESTBS(BBS_ESTBS_SN)
);

-- 게시판_필드
CREATE TABLE FS_BBS_FIELD (
  BBS_FIELD_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_필드_일련번호',
  BBS_ESTBS_SN INT(11) NOT NULL COMMENT '게시판_설정_일련번호',
  BBS_FIELD_CODE VARCHAR(20) NOT NULL COMMENT '게시판_필드_코드',
  BBS_FIELD_NM VARCHAR(20) NOT NULL COMMENT '게시판_필드_명',
  LIST_ORDR SMALLINT(3) NOT NULL COMMENT '목록_순서',
  VIEW_ORDR SMALLINT(3) NOT NULL COMMENT '뷰_순서',
  FIELD_TY VARCHAR(10) NOT NULL COMMENT '필드_타입',
  FIELD_TY_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_타입_활성_여부',
  FIELD_TY_TEXT VARCHAR(255) COMMENT '필드_타입_텍스트',
  FIELD_TY_TEXT_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_타입_텍스트_활성_여부',
  FIELD_USE_AT CHAR(1) NOT NULL COMMENT '필드_사용_여부',
  FIELD_USE_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_사용_활성_여부',
  FIELD_ESSNTL_AT CHAR(1) NOT NULL COMMENT '필드_필수_여부',
  FIELD_ESSNTL_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_필수_활성_여부',
  FIELD_SEARCH_AT CHAR(1) NOT NULL COMMENT '필드_검색_여부',
  FIELD_SEARCH_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_검색_활성_여부',
  FIELD_LIST_AT CHAR(1) NOT NULL COMMENT '필드_목록_여부',
  FIELD_LIST_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_목록_활성_여부',
  FIELD_LIST_SIZE SMALLINT(4) COMMENT '필드_목록_사이즈',
  FIELD_LIST_STYLE VARCHAR(255) COMMENT '필드_목록_스타일',
  FIELD_VIEW_AT CHAR(1) NOT NULL COMMENT '필드_뷰_여부',
  FIELD_VIEW_ACTVTY_AT CHAR(1) NOT NULL COMMENT '필드_뷰_활성_여부',
  PRIMARY KEY(BBS_FIELD_SN),
  FOREIGN KEY(BBS_ESTBS_SN) REFERENCES FS_BBS_ESTBS(BBS_ESTBS_SN)
);

-- 게시판_역할
CREATE TABLE FS_BBS_ROLE (
  BBS_ROLE_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_역할_일련번호',
  BBS_ESTBS_SN INT(11) NOT NULL COMMENT '게시판_설정_일련번호',
  ROLE_SN INT(11) NOT NULL COMMENT '역할_일련번호',
  ROLE_TY VARCHAR(10) NOT NULL COMMENT '역할_타입',
  PRIMARY KEY(BBS_ROLE_SN),
  FOREIGN KEY(BBS_ESTBS_SN) REFERENCES FS_BBS_ESTBS(BBS_ESTBS_SN)
);

-- 게시판_썸네일
CREATE TABLE FS_BBS_THUMB (
  BBS_THUMB_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_썸네일_일련번호',
  BBS_ESTBS_SN INT(11) NOT NULL COMMENT '게시판_설정_일련번호',
  THUMB_NM VARCHAR(20) NOT NULL COMMENT '썸네일_명',
  WIDTH_SIZE SMALLINT(4) COMMENT '가로_사이즈',
  VRTICL_SIZE SMALLINT(4) COMMENT '세로_사이즈',
  PRIMARY KEY(BBS_THUMB_SN),
  FOREIGN KEY(BBS_ESTBS_SN) REFERENCES FS_BBS_ESTBS(BBS_ESTBS_SN)
);

-- 게시판
CREATE TABLE FS_BBS (
  BBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_일련번호',
  BBS_ESTBS_SN INT(11) NOT NULL COMMENT '게시판_설정_일련번호',
  BBS_CTGRY_SN INT(11) COMMENT '게시판_카테고리_일련번호',
  BBS_CTGRY_SUB_SN INT(11) COMMENT '게시판_서브_카테고리_일련번호',
  USER_ID VARCHAR(255) COMMENT '사용자_아이디',
  MNGR_ID VARCHAR(255) COMMENT '관리자_아이디',
  BBS_BEST_SN INT(11) COMMENT '게시판_최상위_일련번호',
  BBS_UPPER_SN INT(11) COMMENT '게시판_상위_일련번호',
  BBS_ORDR SMALLINT(3) NOT NULL COMMENT '게시판_순서',
  BBS_DP SMALLINT(3) NOT NULL COMMENT '게시판_깊이',
  BBS_SJ VARCHAR(255) NOT NULL COMMENT '게시판_제목',
  BBS_CN BLOB COMMENT '게시판_내용',
  REGISTER_NM VARCHAR(60) COMMENT '등록자_명',
  REGIST_PW VARCHAR(255) COMMENT '등록_비밀번호',
  NOTICE_AT CHAR(1) NOT NULL COMMENT '공지_여부',
  SECRET_AT CHAR(1) NOT NULL COMMENT '비밀_여부',
  RDCNT INT(11) NOT NULL COMMENT '조회수',
  CM_CO INT(11) NOT NULL COMMENT '댓글_개수',
  BBS_ETC1 VARCHAR(255) COMMENT '게시판_기타1',
  BBS_ETC2 VARCHAR(255) COMMENT '게시판_기타2',
  BBS_ETC3 VARCHAR(255) COMMENT '게시판_기타3',
  BBS_ETC4 VARCHAR(255) COMMENT '게시판_기타4',
  BBS_ETC5 VARCHAR(255) COMMENT '게시판_기타5',
  BBS_ETC6 VARCHAR(255) COMMENT '게시판_기타6',
  BBS_ETC7 VARCHAR(255) COMMENT '게시판_기타7',
  BBS_ETC8 VARCHAR(255) COMMENT '게시판_기타8',
  BBS_ETC9 VARCHAR(255) COMMENT '게시판_기타9',
  BBS_ETC10 VARCHAR(255) COMMENT '게시판_기타10',
  BBS_ETC11 VARCHAR(255) COMMENT '게시판_기타11',
  BBS_ETC12 VARCHAR(255) COMMENT '게시판_기타12',
  BBS_ETC13 VARCHAR(255) COMMENT '게시판_기타13',
  BBS_ETC14 VARCHAR(255) COMMENT '게시판_기타14',
  BBS_ETC15 VARCHAR(255) COMMENT '게시판_기타15',
  BBS_ETC16 VARCHAR(255) COMMENT '게시판_기타16',
  BBS_ETC17 VARCHAR(255) COMMENT '게시판_기타17',
  BBS_ETC18 VARCHAR(255) COMMENT '게시판_기타18',
  BBS_ETC19 VARCHAR(255) COMMENT '게시판_기타19',
  BBS_ETC20 VARCHAR(255) COMMENT '게시판_기타20',
  --BBS_SALT VARCHAR(255) COMMENT '게시판_솔트',
  DELETE_AT CHAR(1) NOT NULL COMMENT '삭제_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  UPDT_IP VARCHAR(20) NOT NULL COMMENT '수정_아이피',
  PRIMARY KEY(BBS_SN),
  FOREIGN KEY(BBS_ESTBS_SN) REFERENCES FS_BBS_ESTBS(BBS_ESTBS_SN),
  FOREIGN KEY(BBS_CTGRY_SN) REFERENCES FS_BBS_CTGRY(BBS_CTGRY_SN)
);

ALTER TABLE fs_bbs ADD BBS_SALT VARCHAR( 255 ) NULL COMMENT '게시판_솔트' AFTER BBS_ETC20 ;

-- 게시판_댓글
CREATE TABLE FS_BBS_CM (
  BBS_CM_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '게시판_댓글_일련번호',
  BBS_SN INT(11) NOT NULL COMMENT '게시판_일련번호',
  USER_ID VARCHAR(255) COMMENT '사용자_아이디',
  MNGR_ID VARCHAR(255) COMMENT '관리자_아이디',
  BBS_CM_BEST_SN INT(11) COMMENT '게시판_댓글_최상위_일련번호',
  BBS_CM_UPPER_SN INT(11) COMMENT '게시판_댓글_상위_일련번호',
  BBS_CM_ORDR SMALLINT(3) NOT NULL COMMENT '게시판_댓글_순서',
  BBS_CM_DP SMALLINT(3) NOT NULL COMMENT '게시판_댓글_깊이',
  BBS_CM_CN TEXT NOT NULL COMMENT '게시판_댓글_내용',
  REGISTER_NM VARCHAR(60) COMMENT '등록자_명',
  REGIST_PW VARCHAR(255) COMMENT '등록_비밀번호',
  ANSWER_CO INT(11) NOT NULL COMMENT '답글_개수',
  DELETE_AT CHAR(1) NOT NULL COMMENT '삭제_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  UPDT_IP VARCHAR(20) NOT NULL COMMENT '수정_아이피',
  PRIMARY KEY(BBS_CM_SN),
  FOREIGN KEY(BBS_SN) REFERENCES FS_BBS(BBS_SN)
);

-- 분류 뎁스확인 함수
DELIMITER $$

CREATE DEFINER=root@% FUNCTION fncItmListChildDp(_itm_id VARCHAR(40), _org_id VARCHAR(40), _tbl_id VARCHAR(40), _obj_var_id VARCHAR(40))
	RETURNS int(11)
BEGIN
	DECLARE result INT DEFAULT 1;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET @id = NULL;

	IF _itm_id IS NULL THEN
		RETURN 1;
	END IF;

	LOOP
		SELECT	UP_ITM_ID INTO @id
		FROM	TN_ITM_LIST
		WHERE	ORG_ID = _org_id
				AND TBL_ID = _tbl_id
				AND OBJ_VAR_ID = _obj_var_id
				AND ITM_ID = _itm_id
		LIMIT 1;

		IF @id IS NULL THEN
			SET result = result + 1;
			RETURN result;
		END IF;

		SET result = result + 1;
		SET _itm_id = @id;
	END LOOP;
END $$

DELIMITER ;

-- e-지방지표 관리
CREATE TABLE FS_IX_ESTBS (
  IX_ESTBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '지표_설정_일련번호',
  IX_ESTBS_BEST_SN INT(11) COMMENT '지표_설정_최상위_일련번호',
  IX_ESTBS_UPPER_SN INT(11) COMMENT '지표_설정_상위_일련번호',
  IX_ESTBS_ORDR SMALLINT(3) NOT NULL COMMENT '지표_설정_순서',
  IX_ESTBS_DP SMALLINT(3) NOT NULL COMMENT '지표_설정_깊이',
  IX_ESTBS_NM VARCHAR(60) NOT NULL COMMENT '지표_설정_명',
  IX_ESTBS_CODE VARCHAR(60) COMMENT '지표_설정_코드',
  IX_ESTBS_TAG TEXT COMMENT '지표_설정_태그',
  ATCHMNFL_IMAGE VARCHAR(200) COMMENT '첨부파일_이미지',
  FLPTH VARCHAR(255) COMMENT '파일경로',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(IX_ESTBS_SN)
);

-- 콘텐츠_변경이력
CREATE TABLE FS_CNTNTS_CHGHST (
  CNTNTS_CHGHST_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '콘텐츠_변경이력_일련번호',
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  CNTNTS_CHGHST_CN BLOB,
  REGIST_ID VARCHAR(30) NOT NULL COMMENT '등록_아이디',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(CNTNTS_CHGHST_SN),
  FOREIGN KEY(MENU_SN) REFERENCES FS_USER_MENU(MENU_SN)
);

-- 접속자_통계
CREATE TABLE FS_CONECTR_STATS (
  CONECTR_STATS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '접속자_통계_일련번호',
  STATS_YEAR SMALLINT(4) NOT NULL COMMENT '통계_년도',
  STATS_MONTH SMALLINT(2) NOT NULL COMMENT '통계_월',
  STATS_DATE SMALLINT(2) NOT NULL COMMENT '통계_일',
  STATS_HOUR SMALLINT(2) NOT NULL COMMENT '통계_시',
  STATS_MIN SMALLINT(2) NOT NULL COMMENT '통계_분',
  STATS_SEC SMALLINT(2) NOT NULL COMMENT '통계_초',
  STATS_WEEK CHAR(2) NOT NULL COMMENT '통계_주',
  STATS_OPERSYSM VARCHAR(255) COMMENT '통계_운영체제',
  STATS_LOCALE VARCHAR(10) COMMENT '통계_국가언어',
  STATS_REF VARCHAR(255) COMMENT '통계_리퍼러',
  STATS_BRWSR_NM VARCHAR(20) COMMENT '통계_브라우저_명',
  STATS_BRWSR_VER VARCHAR(20) COMMENT '통계_브라우저_버전',
  STATS_PLTFOM VARCHAR(50) COMMENT '통계_플랫폼',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(CONECTR_STATS_SN, REGIST_DE)
);

	-- 접속자_통계 파티션 설정
	ALTER TABLE FS_CONECTR_STATS
	PARTITION BY RANGE (YEAR(REGIST_DE))
	SUBPARTITION BY HASH (MONTH(REGIST_DE))
	SUBPARTITIONS 12 (
		PARTITION conectr_stats_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION conectr_stats_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION conectr_stats_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION conectr_stats_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION conectr_stats_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION conectr_stats_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION conectr_stats_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION conectr_stats_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION conectr_stats_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION conectr_stats_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION conectr_stats_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION conectr_stats_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION conectr_stats_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION conectr_stats_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION conectr_stats_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION conectr_stats_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION conectr_stats_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION conectr_stats_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION conectr_stats_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION conectr_stats_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION conectr_stats_max VALUES LESS THAN MAXVALUE
	);

-- 접속자_통계_메뉴
CREATE TABLE FS_CONECTR_STATS_MENU (
  CONECTR_STATS_MENU_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '접속자_통계_메뉴_일련번호',
  MENU_SN CHAR(13) NOT NULL COMMENT '메뉴_일련번호',
  STATS_YEAR SMALLINT(4) NOT NULL COMMENT '통계_년도',
  STATS_MONTH SMALLINT(2) NOT NULL COMMENT '통계_월',
  STATS_DATE SMALLINT(2) NOT NULL COMMENT '통계_일',
  STATS_HOUR SMALLINT(2) NOT NULL COMMENT '통계_시',
  STATS_MIN SMALLINT(2) NOT NULL COMMENT '통계_분',
  STATS_SEC SMALLINT(2) NOT NULL COMMENT '통계_초',
  STATS_WEEK CHAR(2) NOT NULL COMMENT '통계_주',
  STATS_OPERSYSM VARCHAR(255) COMMENT '통계_운영체제',
  STATS_LOCALE VARCHAR(10) COMMENT '통계_국가언어',
  STATS_REF VARCHAR(255) COMMENT '통계_리퍼러',
  STATS_BRWSR_NM VARCHAR(20) COMMENT '통계_브라우저_명',
  STATS_BRWSR_VER VARCHAR(20) COMMENT '통계_브라우저_버전',
  STATS_PLTFOM VARCHAR(50) COMMENT '통계_플랫폼',
  REGIST_IP VARCHAR(20) NOT NULL COMMENT '등록_아이피',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(CONECTR_STATS_MENU_SN, REGIST_DE)
);

	-- 접속자_통계_메뉴 파티션 설정
	ALTER TABLE FS_CONECTR_STATS_MENU
	PARTITION BY RANGE (YEAR(REGIST_DE))
	SUBPARTITION BY HASH (MONTH(REGIST_DE))
	SUBPARTITIONS 12 (
		PARTITION conectr_stats_menu_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
		PARTITION conectr_stats_menu_max VALUES LESS THAN MAXVALUE
	);
	
-- 스크랩
CREATE TABLE FS_SCRAP (
  SCRAP_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '스크랩_일련번호',
  USER_ID VARCHAR(255) NOT NULL COMMENT '사용자_아이디',
  SCRAP_NM VARCHAR(255) NOT NULL COMMENT '스크랩_명',
  SCRAP_TAG TEXT COMMENT '스크랩_태그',
  SCRAP_ETC1 VARCHAR(255) COMMENT '스크랩_기타1',
  SCRAP_ETC2 VARCHAR(255) COMMENT '스크랩_기타2',
  SCRAP_ETC3 VARCHAR(255) COMMENT '스크랩_기타3',
  SCRAP_ETC4 VARCHAR(255) COMMENT '스크랩_기타4',
  SCRAP_ETC5 VARCHAR(255) COMMENT '스크랩_기타5',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(SCRAP_SN)
);

-- 읍면동 관리
CREATE TABLE FS_EMD_ESTBS (
  EMD_ESTBS_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '읍면동_설정_일련번호',
  EMD_NM VARCHAR(30) NOT NULL COMMENT '읍면동_명',
  CRDNT_LT VARCHAR(30) NOT NULL COMMENT '좌표_위도',
  CRDNT_LO VARCHAR(30) NOT NULL COMMENT '좌표_경도',
  USE_AT CHAR(1) NOT NULL COMMENT '사용_여부',
  ODSN_CD VARCHAR(20) COMMENT '노인_코드',
  JOB_CD VARCHAR(20) COMMENT '일자리_코드',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(EMD_ESTBS_SN)
) COMMENT '읍면동_설정';

-- 2020-02-23 내부 SSO 연동 설정
ALTER TABLE FS_MNGR ADD MNGR_SSO_AT CHAR(1) NOT NULL DEFAULT 'N' COMMENT '관리자_SSO연동_여부' AFTER MNGR_SALT;

-- 교통사고_API
CREATE TABLE FS_TFCACD (
  TFCACD_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '교통사고_일련번호',
  TFCACD_SJ VARCHAR(50) NOT NULL COMMENT '교통사고_제목',
  TFCACD_CD VARCHAR(10) NOT NULL COMMENT '교통사고_코드',
  TFCACD_YEAR_CD VARCHAR(20) NOT NULL COMMENT '교통사고_연도_코드',
  TFCACD_ETC1 VARCHAR(20) COMMENT '교통사고_기타1',
  TFCACD_ETC2 VARCHAR(20) COMMENT '교통사고_기타2',
  TFCACD_ETC3 VARCHAR(20) COMMENT '교통사고_기타3',
  TFCACD_ETC4 VARCHAR(20) COMMENT '교통사고_기타4',
  TFCACD_ETC5 VARCHAR(20) COMMENT '교통사고_기타5',
  TFCACD_ETC6 VARCHAR(20) COMMENT '교통사고_기타6',
  TFCACD_ETC7 VARCHAR(20) COMMENT '교통사고_기타7',
  TFCACD_ETC8 VARCHAR(20) COMMENT '교통사고_기타8',
  TFCACD_ETC9 VARCHAR(20) COMMENT '교통사고_기타9',
  TFCACD_ETC10 VARCHAR(20) COMMENT '교통사고_기타10',
  PRIMARY KEY(TFCACD_SN)
) COMMENT '교통사고';

-- 첨부파일 관리
CREATE TABLE FS_ATCHMNFL_MANAGE (
  ATCHMNFL_MANAGE_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '첨부파일_관리_일련번호',
  ATCHMNFL_SN INT(11) NOT NULL COMMENT '첨부파일_일련번호',
  REGIST_DT DATETIME NOT NULL COMMENT '등록_일자',
  PRIMARY KEY(ATCHMNFL_MANAGE_SN)
) COMMENT '첨부파일_관리';

-- 세종시 전입자수/사유별 구성비 (20/04/22)
CREATE TABLE FS_TRNSFRN_CMPNTRT (
  CMPNTRT_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '구성비_일련번호',
  MNGR_SN INT(11) COMMENT '관리자_일련번호',
  CMPNTRT_YEAR SMALLINT(4) NOT NULL COMMENT '구성비_년도',
  CMPNTRT_TR_OCCP MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_직업',
  CMPNTRT_MT_OCCP MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_직업',
  CMPNTRT_MV_OCCP MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_직업',
  CMPNTRT_TR_FAMILY MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_가족',
  CMPNTRT_MT_FAMILY MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_가족',
  CMPNTRT_MV_FAMILY MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_가족',
  CMPNTRT_TR_HOUSE MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_주택',
  CMPNTRT_MT_HOUSE MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_주택',
  CMPNTRT_MV_HOUSE MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_주택',
  CMPNTRT_TR_EDC MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_교육',
  CMPNTRT_MT_EDC MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_교육',
  CMPNTRT_MV_EDC MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_교육',
  CMPNTRT_TR_LFNRN MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_주거환경',
  CMPNTRT_MT_LFNRN MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_주거환경',
  CMPNTRT_MV_LFNRN MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_주거환경',
  CMPNTRT_TR_NTVR MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_자연환경',
  CMPNTRT_MT_NTVR MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_자연환경',
  CMPNTRT_MV_NTVR MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_자연환경',
  CMPNTRT_TR_ETC MEDIUMINT(7) NOT NULL COMMENT '구성비_전입_기타',
  CMPNTRT_MT_ETC MEDIUMINT(7) NOT NULL COMMENT '구성비_전출_기타',
  CMPNTRT_MV_ETC MEDIUMINT(7) NOT NULL COMMENT '구성비_순이동_기타',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(CMPNTRT_SN)
) COMMENT '전입자_구성비';

-- 시작님 지시사항 관리
CREATE TABLE FS_DRCT (
  DRCT_SN INT(11) NOT NULL AUTO_INCREMENT COMMENT '지시사항_일련번호',
  MNGR_SN INT(11) COMMENT '관리자_일련번호',
  DRCT_SNO VARCHAR(20) COMMENT '지시사항_연번',
  DRCT_SLNO VARCHAR(20) COMMENT '지시사항_부번',
  DRCT_DATE VARCHAR(10) COMMENT '지시사항_지시일자',
  DRCT_STTUS CHAR(1) NOT NULL COMMENT '지시사항_상태',
  DRCT_GUK VARCHAR(30) COMMENT '지시사항_실국',
  DRCT_DEPT VARCHAR(30) COMMENT '지시사항_부서',
  DRCT_CHARGER VARCHAR(20) COMMENT '지시사항_담당자',
  DRCT_CTTPC VARCHAR(20) COMMENT '지시사항_연락처',
  DRCT_CN TEXT NOT NULL COMMENT '지시사항_지시내용',
  DRCT_HIST TEXT COMMENT '지시사항_이력사항',
  REGIST_DE DATETIME NOT NULL COMMENT '등록_일자',
  UPDT_DE DATETIME NOT NULL COMMENT '수정_일자',
  PRIMARY KEY(DRCT_SN)
) COMMENT '지시사항';

-- 세입내역
CREATE TABLE V_FIOS_TBM_REVDESC (
  LOCAL_GOV_CD CHAR(7) NOT NULL COMMENT '자치단체코드',
  FIS_YEAR CHAR(4) NOT NULL COMMENT '회계연도',
  FIS_FG_CD CHAR(3) NOT NULL COMMENT '회계구분코드',
  FIS_FG_NM VARCHAR(200) NOT NULL COMMENT '회계구분명',
  YMD CHAR(8) NOT NULL COMMENT '일자',
  SEQ SMALLINT(3) NOT NULL COMMENT '순번',
  REV_CD CHAR(5) NOT NULL COMMENT '세입코드',
  REV_CD_NM VARCHAR(50) NOT NULL COMMENT '세입코드_명',
  ACCUM_AMT BIGINT(17) NOT NULL COMMENT '전일누계',
  DAY_INC_AMT BIGINT(17) NOT NULL COMMENT '당일수입액',
  DAY_EXC_RESTO_AMT BIGINT(17) NOT NULL COMMENT '당일과오납반확액',
  DAY_ACCT_RV_AMT BIGINT(17) NOT NULL COMMENT '당일과목경정액',
  TRANSM_DATE DATE NOT NULL COMMENT '전송일시',
  DEL_YN CHAR(1) NOT NULL COMMENT '삭제여부'
) COMMENT '세입내역';

ALTER TABLE V_FIOS_TBM_REVDESC ADD INDEX V_FIOS_TBM_REVDESC_IDX (YMD, DEL_YN);

-- 세부사업별 예산현액 및 지출액
CREATE TABLE V_FIOS_TBM_TECURRAMT (
  FIS_YEAR CHAR(4) NOT NULL COMMENT '회계연도',
  FIS_FG_CD CHAR(3) NOT NULL COMMENT '회계구분코드',
  FIS_FG_NM VARCHAR(200) NOT NULL COMMENT '회계구분',
  DEPT_CD CHAR(7) NOT NULL COMMENT '부서코드',
  DEPT_NM VARCHAR(200) NOT NULL COMMENT '부서명',
  PBIZ_CD CHAR(16) NOT NULL COMMENT '정책사업코드',
  PBIZ_NM VARCHAR(200) NOT NULL COMMENT '정책사업명',
  UBIZ_CD CHAR(16) NOT NULL COMMENT '단위사업코드',
  UBIZ_NM VARCHAR(200) NOT NULL COMMENT '단위사업명',
  DBIZ_CD CHAR(16) NOT NULL COMMENT '세부사업코드',
  DBIZ_NM VARCHAR(200) NOT NULL COMMENT '세부사업명',
  SUBSD_BGT_FG VARCHAR(3) NOT NULL COMMENT '사업구분코드',
  SUBSD_BGT_FG_NM VARCHAR(32) NOT NULL COMMENT '사업구분',
  BGT_CURR_AMT BIGINT(17) NOT NULL COMMENT '예산현액',
  NATN_CURR_AMT BIGINT(17) NOT NULL COMMENT '국비',
  SIDO_CURR_AMT BIGINT(17) NOT NULL COMMENT '도비',
  SIGUNGU_CURR_AMT BIGINT(17) NOT NULL COMMENT '시군구비',
  EXPD_AMT BIGINT(17) NOT NULL COMMENT '지출액',
  FLD_CD CHAR(3) NOT NULL COMMENT '분야코드',
  FLD_NM VARCHAR(50) NOT NULL COMMENT '분야',
  BIZ_START_YMD CHAR(8) COMMENT '사업시작일자',
  BIZ_END_YMD CHAR(8) COMMENT '사업종료일자',
  COMPO_AMT BIGINT(17) COMMENT '편성액',
  FORWD_AMT BIGINT(17) COMMENT '이월액',
  CHNG_AMT BIGINT(17) COMMENT '변경금액',
  ETC_AMT BIGINT(17) COMMENT '수입대체경비'
) COMMENT '지출액';

ALTER TABLE V_FIOS_TBM_TECURRAMT ADD INDEX V_FIOS_TBM_TECURRAMT_IDX (FIS_YEAR);



--앱버전 관리
CREATE TABLE fs_app_version (
  OS_SN int(10) NOT NULL,
  OS varchar(50) NOT NULL,
  IOS varchar(45) DEFAULT NULL,
  ANDROID varchar(45) DEFAULT NULL,
  REGIST_DT datetime DEFAULT NULL,
  REGIST_ID varchar(30) DEFAULT NULL,
  UPDT_DT datetime DEFAULT NULL,
  UPDT_ID varchar(30) DEFAULT NULL,
  PRIMARY KEY (OS_SN)
) COMMENT='앱버전 관리'

--회원관리 접속로그
CREATE TABLE fs_user_login_hist (
  LOGIN_HIST_SN int(11) NOT NULL AUTO_INCREMENT COMMENT '로그인_이력_일련번호',
  user_SN int(11) NOT NULL COMMENT '유저_일련번호',
  SESION_ID varchar(100) NOT NULL COMMENT '세션_아이디',
  LOGIN_IP varchar(20) NOT NULL COMMENT '로그인_아이피',
  LOGIN_PLTFOM varchar(20) DEFAULT NULL COMMENT '로그인_플랫폼',
  LOGIN_BRWSR_NM varchar(20) NOT NULL COMMENT '로그인_브라우저_명',
  LOGIN_BRWSR_VER varchar(10) DEFAULT NULL COMMENT '로그인_브라우저_버전',
  LOGIN_BGNDE datetime NOT NULL COMMENT '로그인_시작일',
  LOGIN_ENDDE datetime DEFAULT NULL COMMENT '로그인_종료일',
  PRIMARY KEY (LOGIN_HIST_SN,LOGIN_BGNDE)
) COMMENT='유저_로그인_이력'
 PARTITION BY RANGE (year(LOGIN_BGNDE))
SUBPARTITION BY HASH (month(LOGIN_BGNDE))
SUBPARTITIONS 12
(PARTITION user_login_hist_2019 VALUES LESS THAN (2020) ENGINE = InnoDB,
 PARTITION user_login_hist_2020 VALUES LESS THAN (2021) ENGINE = InnoDB,
 PARTITION user_login_hist_2021 VALUES LESS THAN (2022) ENGINE = InnoDB,
 PARTITION user_login_hist_2022 VALUES LESS THAN (2023) ENGINE = InnoDB,
 PARTITION user_login_hist_2023 VALUES LESS THAN (2024) ENGINE = InnoDB,
 PARTITION user_login_hist_2024 VALUES LESS THAN (2025) ENGINE = InnoDB,
 PARTITION user_login_hist_2025 VALUES LESS THAN (2026) ENGINE = InnoDB,
 PARTITION user_login_hist_2026 VALUES LESS THAN (2027) ENGINE = InnoDB,
 PARTITION user_login_hist_2027 VALUES LESS THAN (2028) ENGINE = InnoDB,
 PARTITION user_login_hist_2028 VALUES LESS THAN (2029) ENGINE = InnoDB,
 PARTITION user_login_hist_2029 VALUES LESS THAN (2030) ENGINE = InnoDB,
 PARTITION user_login_hist_2030 VALUES LESS THAN (2031) ENGINE = InnoDB,
 PARTITION user_login_hist_2031 VALUES LESS THAN (2032) ENGINE = InnoDB,
 PARTITION user_login_hist_2032 VALUES LESS THAN (2033) ENGINE = InnoDB,
 PARTITION user_login_hist_2033 VALUES LESS THAN (2034) ENGINE = InnoDB,
 PARTITION user_login_hist_2034 VALUES LESS THAN (2035) ENGINE = InnoDB,
 PARTITION user_login_hist_2035 VALUES LESS THAN (2036) ENGINE = InnoDB,
 PARTITION user_login_hist_2036 VALUES LESS THAN (2037) ENGINE = InnoDB,
 PARTITION user_login_hist_2037 VALUES LESS THAN (2038) ENGINE = InnoDB,
 PARTITION user_login_hist_2038 VALUES LESS THAN (2039) ENGINE = InnoDB,
 PARTITION user_login_hist_max VALUES LESS THAN MAXVALUE ENGINE = InnoDB)
 
 
CREATE TABLE FS_BBS_CTGRY_SUB (
  BBS_CTGRY_SUB_SN int(11) NOT NULL AUTO_INCREMENT COMMENT '서브_카테고리_일련번호',
  BBS_CTGRY_SN int(11) NOT NULL COMMENT '상위_카테고리_일련번호',
  CTGRY_NM varchar(255) NOT NULL COMMENT '카테고리_명',
  PRIMARY KEY (BBS_CTGRY_SUB_SN),
  KEY BBS_CTGRY_SN (BBS_CTGRY_SN),
  CONSTRAINT fs_bbs_ctgry FOREIGN KEY (BBS_CTGRY_SN) REFERENCES fs_bbs_ctgry (BBS_CTGRY_SN)
) COMMENT='게시판_서브_카테고리'



CREATE TABLE FS_AUTH_UPLOAD (
  AU_SN int(11) NOT NULL AUTO_INCREMENT,
  USER_NM varchar(20) NOT NULL,
  USER_BIRTH varchar(10) DEFAULT NULL,
  USER_SEX char(1) DEFAULT NULL,
  USER_TELNO varchar(20) DEFAULT NULL,
  USER_ZIP varchar(10) DEFAULT NULL,
  USER_ADRES_BASS varchar(100) DEFAULT NULL,
  USER_ADRES_DETAIL varchar(100) DEFAULT NULL,
  USER_EMAIL varchar(50) DEFAULT NULL,
  NOTE_SN varchar(15) NOT NULL,
  AUTH_SN varchar(15) NOT NULL,
  COURSE_NM varchar(100) DEFAULT NULL,
  COURSE_START varchar(200) DEFAULT NULL,
  AUTH_STATUS char(1) DEFAULT NULL,
  AUTH_CENTER varchar(100) DEFAULT NULL,
  PUB_DE varchar(20) DEFAULT NULL,
  REGIST_DE datetime NOT NULL,
  UPDT_DE datetime DEFAULT NULL,
  PRIMARY KEY (AU_SN)
) COMMENT='종주인증 DB업로드'

CREATE TABLE fs_auth_web (
  AUTH_SN int(11) NOT NULL AUTO_INCREMENT,
  ROAD_CD varchar(45) DEFAULT NULL,
  AUTH_CD varchar(45) NOT NULL,
  AUTH_STATE varchar(45) DEFAULT NULL,
  USER_SN int(11) DEFAULT NULL,
  REGIST_DE datetime DEFAULT NULL,
  NOTE_SN varchar(45) NOT NULL,
  PRIMARY KEY (AUTH_SN)
) COMMENT='종주인증_웹'

CREATE TABLE fs_auth_note (
  LIST_SN int(11) NOT NULL AUTO_INCREMENT COMMENT '인증번호 목록 번호',
  USER_SN int(11) NOT NULL COMMENT '유저 시리얼번호',
  NOTE_SN varchar(13) NOT NULL COMMENT '인증수첩 번호',
  AUTH_YN char(1) DEFAULT NULL COMMENT '인증수첩 대표 여부',
  REGIST_DE datetime NOT NULL,
  UPDT_DE datetime DEFAULT NULL,
  PRIMARY KEY (LIST_SN)
) COMMENT='회원 인증수첩 목록'

CREATE TABLE fs_auth_road (
  ROAD_SN int(11) NOT NULL AUTO_INCREMENT,
  ROAD_CD varchar(45) DEFAULT NULL,
  ROAD_NM varchar(100) DEFAULT NULL,
  ROAD_ORDR int(11) DEFAULT NULL,
  USE_AT varchar(1) NOT NULL DEFAULT 'Y',
  OLD_CD varchar(45) DEFAULT NULL,
  PRIMARY KEY (ROAD_SN)
) COMMENT='종주길 목록'

CREATE TABLE fs_auth_road_sub (
  CD_SN int(11) NOT NULL AUTO_INCREMENT,
  ROAD_CD varchar(45) NOT NULL,
  AUTH_CD varchar(45) NOT NULL,
  AUTH_NM varchar(45) DEFAULT NULL,
  AUTH_ORDR int(11) DEFAULT NULL,
  AUTH_TYPE int(1) DEFAULT NULL,
  USE_AT varchar(1) DEFAULT 'Y',
  PRIMARY KEY (CD_SN)
) COMMENT='인증구간별 인증소'

